# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

def commonPods
	pod 'Firebase'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
	pod 'Freddy', '~> 3.0.0'
	pod 'Alamofire', '~> 4.0'
end

target 'Luna' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  commonPods
end
  
  # Pods for Luna

  target 'LunaTests' do
    commonPods
  end
