# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'Luna' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Freddy', '~> 3.0.0'
  pod 'Alamofire', '~> 4.0'
  
  # Pods for Luna

  target 'LunaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
